settings:
  project_id: "devloop"
  color_logs: true
  prefix_logs: true
  prefix_max_length: 15

rules:
  # Go Backend Development & Testing
  - name: "backend"
    color: "blue"
    watch:
      - action: "include"
        patterns:
          - "**/*.go"
          - "go.mod"
          - "go.sum"
    commands:
      - "echo '🔧 Building Devloop Binary into GOBIN...'"
      - "make install"
      - devloop --version
