name: ml-dev
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  
  # Core scientific computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  
  # Deep learning
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - tensorflow>=2.13.0
  
  # Data processing
  - pyarrow>=12.0.0
  - dask>=2023.6.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # Jupyter
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipywidgets>=8.0.0
  
  # Development tools
  - black
  - flake8
  - isort
  - mypy
  - pytest
  - pytest-cov
  
  # CUDA (optional - will only install if CUDA-capable GPU detected)
  - cudatoolkit=11.8
  
  # Additional packages via pip
  - pip:
    - mlflow>=2.5.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - optuna>=3.2.0
    - shap>=0.42.0
    - evidently>=0.4.0
    - great-expectations>=0.17.0
    - wandb>=0.15.0